chapter5:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: oluwafemisobakin
      password: Derindura2577@
      port: 5432
      dbname: mlops
      schema: raw_data